# NETLIFY CMS CONFIG
backend:
  name: git-gateway
  branch: main

site_url: https://replikamasterworks.com

# publish_mode: editorial_workflow
media_folder: /static/assets/uploads

collections: # A list of collections the CMS should be able to edit


  - name: 'siteCMS'
    label: 'Site CMS'
    description: >
      Edit the Fields below to change the relevant info on the site
    editor:
      preview: true
    files:

      - name: 'contact'
        label: 'Contact'
        file: '/src/lib/data/contact.json'
        description: 'Contact Info'
        fields:
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Address', name: 'address', widget: 'string' }

      - name: 'footer_misc'
        label: 'Footer Misc'
        file: '/src/lib/data/misc.json'
        description: 'Misc Footer Strings'
        fields:
          - { label: 'Footer 1', name: 'footer_1', widget: 'string', default: 'Copyright 2022' }
          - { label: 'Footer 2', name: 'footer_2', widget: 'string', default: 'REPLIKA MASTERWORKS PDX' }

      - name: 'page_content'
        label: 'Page Content'
        file: '/src/lib/data/page_content.json'
        description: 'Page Content - Text and Images'
        fields:

          - label: 'Design'
            name: 'design'
            widget: 'object'
            fields:
              - { label: 'Subheading', name: subheading, widget: string }
              - { label: 'Body', name: body, widget: text }
              - label: "Design Image"
                name: "design_image"
                widget: "image"
                choose_url: false
                media_library:
                  config:
                    multiple: false

          - label: 'Scan'
            name: 'scan'
            widget: 'object'
            fields:
              - { label: 'Subheading', name: subheading, widget: string }
              - { label: 'Body', name: body, widget: text }
              - label: "Scan Image"
                name: "scan_image"
                widget: "image"
                choose_url: false
                media_library:
                  config:
                    multiple: false

          - label: 'Print'
            name: 'print'
            widget: 'object'
            fields:
              - { label: 'Subheading', name: subheading, widget: string }
              - { label: 'Body', name: body, widget: text }
              - label: "Print Image"
                name: "print_image"
                widget: "image"
                choose_url: false
                media_library:
                  config:
                    multiple: false


          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            fields:
              - label: "Contact Image"
                name: "contact_image"
                widget: "image"
                media_folder: "/static/assets/netlifycms/contact"
                choose_url: false
                media_library:
                  config:
                    multiple: false